-- DDL

CREATE DATABASE ProjetoSENAI;


Use ProjetoSENAI;


CREATE TABLE Escola (
IdEscola INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(50),
Logradouro VARCHAR(50),
Numero VARCHAR(50),
Complemento VARCHAR(50),
Bairro VARCHAR(50),
Cep VARCHAR(10)
);

CREATE TABLE Categoria (
IdCategoria INT PRIMARY KEY IDENTITY NOT NULL,
Tipo VARCHAR(50)
);

CREATE TABLE Curso (
IdCurso INT PRIMARY KEY IDENTITY NOT NULL,
NomeCurso VARCHAR(50)
);

CREATE TABLE Objetivo(
IdObjetivo INT PRIMARY KEY IDENTITY NOT NULL,
NomeObjetivo VARCHAR(50),
Descricao VARCHAR(250),
IdCategoria INT FOREIGN KEY REFERENCES Categoria (IdCategoria)
);

CREATE TABLE Professor(
IdProfessor INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(50),
Cpf VARCHAR(50),
Registro VARCHAR(50),
Email VARCHAR(150),
Senha VARCHAR(150),
IdEscola INT FOREIGN KEY REFERENCES Escola (IdEscola)
);

CREATE TABLE Aluno (
IdAluno INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(50),
Cpf VARCHAR(50),
Ra VARCHAR (50),
DataNascim DATETIME,
Email VARCHAR(150),
Senha VARCHAR(150),
IdCurso INT FOREIGN KEY REFERENCES Curso (IdCurso)
);

CREATE TABLE Nota(
IdNota INT PRIMARY KEY IDENTITY NOT NULL,
Resultado DECIMAL,
IdAluno INT FOREIGN KEY REFERENCES Aluno (IdAluno),
IdObjetivo INT FOREIGN KEY REFERENCES Objetivo (IdObjetivo)
);

CREATE TABLE Post (
IdPost INT PRIMARY KEY IDENTITY NOT NULL,
Titulo VARCHAR(50),
Conteudo VARCHAR(250),
DataPost DATETIME,
Imagem VARCHAR(250),
IdAluno INT FOREIGN KEY REFERENCES Aluno (IdAluno),
IdObjetivo INT FOREIGN KEY REFERENCES Objetivo (IdObjetivo)
);

CREATE TABLE Turma (
IdTurma INT PRIMARY KEY IDENTITY NOT NULL,
Identificacao	VARCHAR(50),
Periodo VARCHAR(50),
IdCurso INT FOREIGN KEY REFERENCES Curso (IdCurso),
);

CREATE TABLE AlunoTurma (
IdAlunoTurma INT PRIMARY KEY IDENTITY NOT NULL,
IdTurma INT FOREIGN KEY REFERENCES Turma (IdTurma),
IdAluno INT FOREIGN KEY REFERENCES Aluno (IdAluno)
);

CREATE TABLE ProfessorTurma (
IdProfessorTurma INT PRIMARY KEY IDENTITY NOT NULL,
IdTurma INT FOREIGN KEY REFERENCES Turma (IdTurma),
IdProfessor INT FOREIGN KEY REFERENCES Professor (IdProfessor) 
);

CREATE TABLE Dica (
IdDica INT PRIMARY KEY IDENTITY NOT NULL,
Titulo VARCHAR(50),
Conteudo VARCHAR(250),
Imagem VARCHAR(250),
IdObjetivo INT FOREIGN KEY REFERENCES Objetivo (IdObjetivo),
IdProfessor INT FOREIGN KEY REFERENCES Professor (IdProfessor)
);

CREATE TABLE ObjetivoAluno (
IdObjetivoAluno INT PRIMARY KEY IDENTITY NOT NULL,
IdObjetivo INT FOREIGN KEY REFERENCES Objetivo (IdObjetivo),
IdAluno INT FOREIGN KEY REFERENCES Aluno (IdAluno)
);




