--Cria o banco de dados Artista
CREATE DATABASE Artista;

--Usa o banco de dados (existente) Artista
USE Artista;

--Cria uma entidade(tabela) Estilo
CREATE TABLE Estilo (
IdEstilo INT PRIMARY KEY IDENTITY NOT NULL,
NOME	 VARCHAR(20)
);

CREATE TABLE Artista (
IdArtista	INT PRIMARY KEY IDENTITY NOT NULL,
IdEstilo	INT FOREIGN KEY REFERENCES Estilo (IdEstilo),
NOME		VARCHAR(20)
);

CREATE TABLE Album (
IdAlbum		INT PRIMARY KEY IDENTITY NOT NULL,
IdArtista   INT FOREIGN KEY REFERENCES Artista (IdArtista),
NOME		VARCHAR(20),
TRABALHOS	VARCHAR (100),
MINUTOS		INT,
AVALIACAO	INT
);

CREATE TABLE EstiloAlbum (
IdEstiloAlbum	INT PRIMARY KEY IDENTITY NOT NULL,
IdEstilo		INT FOREIGN KEY REFERENCES Estilo (IdEstilo),
IdAlbum			INT FOREIGN KEY REFERENCES Album (IdAlbum),
NOME			VARCHAR(20)
);

CREATE TABLE Usuario (
IdUsuario   INT PRIMARY KEY IDENTITY NOT NULL,
NOME		VARCHAR(20),
SENHA		VARCHAR(30),
EMAIL		VARCHAR(50),
PERMISSAO	VARCHAR(15),
);
